### ISSUE TITLE
uBO webext doesn't fill entire panel space

### ISSUE THREAD

**Issue by pwd-github** [gorhill/uBlock#2809]
### Describe the issue
While the old, even the hybrid filled the entire panel, the webext leaves an empty space.

### Screenshot in which the issue can be seen
![ubouiissue](https://user-images.githubusercontent.com/203217/28460769-5ec21c06-6e0b-11e7-9e5b-e9ea5eab2073.png)

### Steps for anyone to reproduce the issue
1. Place the uBO icon in the add-ons overflow
2. Open the overflow
3. Click the uBO icon
4. See empty space to the right of the uBO panel

### Your settings
Hide placeholders of blocked elements
Show the number of blocked requests on the icon
Make use of context menu where appropriate
Enable cloud storage support
Disable pre-fetching (to prevent any connection for blocked network requests) 
Disable hyperlink auditing

[If you fail to provide this info, I will mark the issue as invalid. Lists all settings which differs from default settings]

- OS/version: Ubuntu 17.04
- Browser/version: Firefox Nightly
- uBlock Origin version: 1.13.9b0

**Comment by Betsy25** [comment]
Reproducible on Firefox Nightly in Win7 x64

**Comment by gorhill** [comment]
[Unlike the legacy version](https://github.com/gorhill/uBlock/issues/2709), uBO/webext can't control the size of the popup placeholder. This needs to be reported to Firefox, see: <https://bugzilla.mozilla.org/show_bug.cgi?id=1369564>.

**Comment by gorhill** [comment]
Ok I see, uBO is inside the overflow menu, so I can reproduce.

There is also an issue in advanced panel mode, it's being truncated. This is not trivial, so far all popup code never had to assume the popup panel was set in a fixed-width parent frame.

**Comment by gorhill** [comment]
I believe this is related: <https://bugzilla.mozilla.org/show_bug.cgi?id=1373490>.

With the legacy version, uBO was able to adjust its size because if was able to gather knowledge about the current context, that it's panel was being rendered inside the menu. It's not possible to get contextual knowledge with webext. What could help is if the Firefox framework set a specific predefined class name on the panel's `html` element to provide that knowledge, so that an extension could use this class to craft special CSS rules for that case (this is what uBO legacy was doing [with its `portrait` class name](https://github.com/gorhill/uBlock/blob/432818df4fc372c96aa025af1eaed224ff03da31/platform/firefox/vapi-background.js#L3085)).

**Comment by ronjouch** [comment]
Adding a screenshot to add that,

* While in **Standard** mode, this bug merely makes the panel ugly due to weird whitespace around it...
* ... using **Advanced** mode, it means the entire right part of the panel is invisible and unusable:

![ublock-origin-overflow-unusable-advanced-right-part](https://user-images.githubusercontent.com/522085/28930740-e62f28f6-7841-11e7-94b1-64f08453c480.png)

Using Nightly 57.0a1 (2017-08-03) on Linux.

**Comment by emmyemi** [comment]
@gorhill Would it be possible to include a small script to get the visible width of the menu each time it's opened? If it detects that not all of the menu is visible horizontally, it can then apply a different set of style rules.

Alternatively, rewriting the UI with responsive design in mind should alleviate the issue as well.

**Comment by smithfred** [comment]
As this remains unfixed in uBO https://github.com/gorhill/uBlock/issues/2809#issuecomment-320010715 (advanced mode unusable) can be worked around in userChrome.css:

* Option 1: only widen uBO panel - unfortunately the overflow menu subsequently appears in the wrong place (not under the button) if the uBO panel was the last one shown:
```css
#widget-overflow .PanelUI-subView[title^="uBlock Origin"] {
    min-width: 492px !important;
}
```

* Option 2: widen the overflow menu and all extension panels (not as pretty but popover always appears in the right place):
```css
#widget-overflow, #widget-overflow .PanelUI-subView {
    min-width: 492px !important;
}
```

Improved CSS welcome ;)

**Comment by smithfred** [comment]
A better version of option 2:

```css
#widget-overflow .PanelUI-subView {
    min-width: 492px !important;
}
#widget-overflow-mainView {
    max-width: none !important;
    width: 492px !important;
}
#widget-overflow-fixed-list > .toolbarbutton-1 {
    max-width: none !important;
}
```
