### ISSUE TITLE
Document this workaround for Firefox 57+ overflow menu width breaking uBO UI

### ISSUE THREAD

**Issue by smithfred** [gorhill/uBlock#3373]
Per https://github.com/gorhill/uBlock/issues/2809#issuecomment-320010715, the constrained width of the FF57+ overflow menu breaks uBlock's advanced menu.

Since that issue hasn't been fixed on uBO's side since, and as I can't add a comment to that issue since it's *locked* :J, please document somewhere that this can be worked around in userChrome.css with the following:

```css
#widget-overflow .PanelUI-subView[title^="uBlock Origin"] {
    min-width: 500px !important;
}
```
